package:
  name: '{{cookiecutter.repo_name}}'
  version: '0.1.0'

source:
  git_rev: 0.1.0
  git_url: https://github.com/{{cookiecutter.github_organization}}/{{cookiecutter.repo_name}}.git

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  include_recipe: False

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python >=3.8
    - nionswift >=0.16.0,<0.17.0

test:
  imports:
    - {{cookiecutter.org_name}}.{{cookiecutter.lib_name}}
    - {{cookiecutter.org_name}}.{{cookiecutter.lib_name}}.test
    - nionswift_plugin.{{cookiecutter.lib_name}}
    - nionswift_plugin.{{cookiecutter.lib_name}}.test

about:
  home: https://github.com/{{cookiecutter.github_organization}}/{{cookiecutter.repo_name}}
  license: GPL-3.0
  summary: "Library and UI for processing with Nion Swift."
  description: "Library and UI for processing with Nion Swift."

extra:
  recipe-maintainers:
    {{cookiecutter.github_username}}
